### ISSUE TITLE
Please give an example on how to use other themes with the --PALETTE option

### ISSUE THREAD

**Issue by orbitalchicken** [Schrodinger-Hat/ImageGoNord#104]
I am trying to use another theme, for example Monokai, and it's not working:

`python src/cli.py --PALETTE='Monokai' --img='input.png'`

I receive: "[WARNING] No theme specified, use default Nord theme"

What am I not understanding?

**Comment by Wabri** [comment]
Hi @orbitalchicken,

Maybe the help page is a little confused:

```
Theme options:
  --PALETTE[=LIST_COLOR_SET]        the palette can be found on the
                                    src/palettes/ directory (actually there is
                                    only nord), by replace the palette with the
                                    name is possible to select the theme and if
                                    necessary you can specify the set of colors
                                    you want to use.
                                    Ex: python src/cli.py --nord=aur,p,s is
                                    possible to pass the name of the color or
                                    the first character of the name set.
```

You must substitute PALETTE with monokay and not specify as value of PALETTE, in your case the correct command would be:

```
python src/cli.py --monokay --img='input.png'
```

Since monokay has not been divided into subgroups it is not possible to filter, which could be done with nord theme instead using this command:

```
python src/cli.py --nord=aurora,frost --img='input.png'
```

I'll open 2 new issues in order to improve documentation and help command.

Thank you for pointing out this problem 🥇 

I'll close the issue when you confirm that the solution that I gave it works.
