### ISSUE TITLE
Help with adding a palette

### ISSUE THREAD

**Issue by Narmis-E** [Schrodinger-Hat/ImageGoNord#139]
Hi,
I really love this project and would love to contribute by adding a colour palette to the repo. However, I am not sure how to proceed as to building from source to see if using my colourscheme works. I couldn't really find any documentation on how to test locally to ensure the palette will work, like the contributors in the PRs appear to have done.

**Comment by Wabri** [comment]
Hi @Narmis-E, do you want to add to the site or to the cli?

**Comment by Narmis-E** [comment]
I wasn't exactly sure to be honest. I saw that you guys add new palettes to the imagegowild site. I made a fork of the gruvbox-factory cli tool for the [everforest theme](https://github.com/Narmis-E/everforest-factory) but the theme I was looking to add was the rosépine theme.

Sorry about not understanding this whole process 😔

**Comment by Wabri** [comment]
Hi @Narmis-E, 

## Site
If you want to add a palette to the site you can look at:
- `src/ign-frontend/src/assets/palettes` by adding a new json file with all the palettes you want to add
- then into `src/ign-frontend/src/assets/palettes/available-palettes.json` 
- and in the end here `src/ign-frontend/src/views/GoWild.vue` at line 91 should be where the palettes will load and generate the section in the site

## Cli
The cli moved into another repository and by now is currently stalled due to a lack of time, but I think we will resume maintaining and making improvements to the cli driven by the last version v0.1.7 of the imagegonord library that add the video conversion feature https://github.com/Schrodinger-Hat/ImageGoNord-pip/releases/tag/v0.1.7. If you want to take a look into the cli i suggest you to take a tour here https://github.com/Schrodinger-Hat/ImageGoNord-cli

## Conclusion
Thank you very much for your interest, we hope that in the near future, we can go back to developing the project as we did in the beginning. If you want to be part of the community you can join us in the discord server https://discord.com/invite/fSZ6AbFh

**Comment by Narmis-E** [comment]
Thanks, I'll look into it! 👍
