### ISSUE TITLE
CORS Error when not enabling "Filtering"

### ISSUE THREAD

**Issue by Aceto1** [Schrodinger-Hat/ImageGoNord#27]
When I just leave everything on default, the processing takes ages and after it eventually finishes you'll find a CORS error in the console.
![CORS Error](https://user-images.githubusercontent.com/19893244/105841111-6c52c000-5fd4-11eb-92d3-107797b84e59.png)

**Comment by TheJoin95** [comment]
Thank you @Aceto1 for reporting this issue.
This is happening because of the little heroku instance that we are currently using in order to deploy our API.

The heroku istance went in timeout after processing the request for 30sec.
Try to use a smaller resolution image.

We are trying to find some sponsorship to scale up the API service

**Comment by TheJoin95** [comment]
By the way, I would like to change the pattern that I used in JS to suite up the request to the server.
I know I can do it better by providing async processing and a decent UI/UX to let the user wait.

I wanted to this because we could not find any sort of sponsorship to maintain the project at a very great level.
Anyway, I'll work on it as soon as possible

**Comment by Aceto1** [comment]
How much processing power would be needed? I think I have a spare Droplet from DigitalOcean I could provide.

**Comment by TheJoin95** [comment]
I'm sorry for the late answer, we were in a really tough period at work ehe

We deployed a worker process on heroku to process the image in background.
We also deployed a polling endpoint in order to get the result when the job finished.

Heroku is still slow with low memory.
I guess that any droplet would be fine, from a 1GB ram or more.

It needs some computing power to make an image process good.
If you like, you can deploy the `feature/6/api` to your droplet, so we can test it out :)

**Comment by TheJoin95** [comment]
Fixed by publishing the API onto a new VPS on OVH
