### ISSUE TITLE
Ovh is not free

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#72]
In order to keep the site online is necessary to find a way to sponsor the project and limit the accessibility when the coverage dont get the minimum value.

- [ ] rate limit: 5 image per hours when the coverage is **not** achieved monthly (keep the users ip anonymous)
- [ ] free access when the coverage is achieved monthly
- [ ] Use open collective to pay ovh and be transparent https://opencollective.com/schrodinger-hat/projects/image-go-nord
- [ ] Report on the page when the monthly payment is reached or not

**Comment by BugliL** [comment]
What performance is needed to provide the online feature?

**Comment by TheJoin95** [comment]
_The more is the better_

Actually we have a VPS with 2GB RAM, Dual-Core 3.2GHz processor and 20GB SSD. The instance is running the nginx & gunicorn server, plus the redis server in order to serve the queue & event to the demo client website.
The monthly cost is: 10.40€

With this setup the avg convert time (using the avg algorithm) is 20sec for a Full-HD image

**Comment by Wabri** [comment]
This can be marked as resolved
